/**
 * openGym library exercise ids → [name, body part], so history pulled from an
 * openGym instance reads "barbell bench press" instead of "0025".
 *
 * Names and body parts only. They are ExerciseDB v1 metadata (AscendAPI), MIT,
 * as redistributed by hasaneyldrm/exercises-dataset — see openGym NOTICE.md.
 * No openGym (AGPL) code and no exercise media is included here.
 * Generated from openGym frontend/src/lib/exercises-data.js (1324 entries).
 */
export const OPENGYM_EXERCISES: Record<string, [name: string, bodyPart: string]> = {
  "0001": ["3/4 sit-up", "waist"],
  "0002": ["45° side bend", "waist"],
  "0003": ["air bike", "waist"],
  "1512": ["all fours squad stretch", "upper legs"],
  "0006": ["alternate heel touchers", "waist"],
  "0007": ["alternate lateral pulldown", "back"],
  "1368": ["ankle circles", "lower legs"],
  "3293": ["archer pull up", "back"],
  "3294": ["archer push up", "chest"],
  "2355": ["arm slingers hanging bent knee legs", "waist"],
  "2333": ["arm slingers hanging straight legs", "waist"],
  "3214": ["arms apart circular toe touch (male)", "upper legs"],
  "3204": ["arms overhead full sit-up (male)", "waist"],
  "0009": ["assisted chest dip (kneeling)", "chest"],
  "0011": ["assisted hanging knee raise", "waist"],
  "0010": ["assisted hanging knee raise with throw down", "waist"],
  "1708": ["assisted lying calves stretch", "lower legs"],
  "1709": ["assisted lying glutes stretch", "upper legs"],
  "1710": ["assisted lying gluteus and piriformis stretch", "upper legs"],
  "0012": ["assisted lying leg raise with lateral throw down", "waist"],
  "0013": ["assisted lying leg raise with throw down", "waist"],
  "0014": ["assisted motion russian twist", "waist"],
  "0015": ["assisted parallel close grip pull-up", "back"],
  "0016": ["assisted prone hamstring", "upper legs"],
  "1713": ["assisted prone lying quads stretch", "upper legs"],
  "1714": ["assisted prone rectus femoris stretch", "waist"],
  "0017": ["assisted pull-up", "back"],
  "1716": ["assisted seated pectoralis major stretch with stability ball", "chest"],
  "1712": ["assisted side lying adductor stretch", "upper legs"],
  "1758": ["assisted sit-up", "waist"],
  "1431": ["assisted standing chin-up", "back"],
  "1432": ["assisted standing pull-up", "back"],
  "0018": ["assisted standing triceps extension (with towel)", "upper arms"],
  "0019": ["assisted triceps dip (kneeling)", "upper arms"],
  "2364": ["assisted wide-grip chest dip (kneeling)", "chest"],
  "3220": ["astride jumps (male)", "cardio"],
  "3672": ["back and forth step", "cardio"],
  "1314": ["back extension on exercise ball", "back"],
  "3297": ["back lever", "back"],
  "1405": ["back pec stretch", "back"],
  "1473": ["backward jump", "upper legs"],
  "0020": ["balance board", "upper legs"],
  "0968": ["band alternating biceps curl", "upper arms"],
  "0969": ["band alternating v-up", "waist"],
  "0970": ["band assisted pull-up", "back"],
  "0971": ["band assisted wheel rollerout", "waist"],
  "1254": ["band bench press", "chest"],
  "0980": ["band bent-over hip extension", "upper legs"],
  "0972": ["band bicycle crunch", "waist"],
  "0974": ["band close-grip pulldown", "back"],
  "0975": ["band close-grip push-up", "upper arms"],
  "0976": ["band concentration curl", "upper arms"],
  "3117": ["band fixed back close grip pulldown", "back"],
  "3116": ["band fixed back underhand pulldown", "back"],
  "0977": ["band front lateral raise", "shoulders"],
  "0978": ["band front raise", "shoulders"],
  "1408": ["band hip lift", "upper legs"],
  "0979": ["band horizontal pallof press", "waist"],
  "0981": ["band jack knife sit-up", "waist"],
  "0983": ["band kneeling one arm pulldown", "back"],
  "0985": ["band kneeling twisting crunch", "waist"],
  "0984": ["band lying hip internal rotation", "upper legs"],
  "1002": ["band lying straight leg raise", "waist"],
  "0986": ["band one arm overhead biceps curl", "upper arms"],
  "0987": ["band one arm single leg split squat", "upper legs"],
  "0988": ["band one arm standing low row", "back"],
  "0989": ["band one arm twisting chest press", "chest"],
  "0990": ["band one arm twisting seated row", "back"],
  "0991": ["band pull through", "upper legs"],
  "0992": ["band push sit-up", "waist"],
  "0993": ["band reverse fly", "shoulders"],
  "0994": ["band reverse wrist curl", "lower arms"],
  "0996": ["band seated hip internal rotation", "upper legs"],
  "1011": ["band seated twist", "waist"],
  "0997": ["band shoulder press", "shoulders"],
  "1018": ["band shrug", "back"],
  "0998": ["band side triceps extension", "upper arms"],
  "0999": ["band single leg calf raise", "lower legs"],
  "1000": ["band single leg reverse calf raise", "lower legs"],
  "1001": ["band single leg split squat", "upper legs"],
  "1004": ["band squat", "upper legs"],
  "1003": ["band squat row", "upper legs"],
  "1005": ["band standing crunch", "waist"],
  "1022": ["band standing rear delt row", "shoulders"],
  "1007": ["band standing twisting crunch", "waist"],
  "1008": ["band step-up", "upper legs"],
  "1009": ["band stiff leg deadlift", "upper legs"],
  "1023": ["band straight back stiff leg deadlift", "upper legs"],
  "1010": ["band straight leg deadlift", "back"],
  "1012": ["band twisting overhead press", "shoulders"],
  "1369": ["band two legs calf raise - (band under both legs) v. 2", "lower legs"],
  "1013": ["band underhand pulldown", "back"],
  "1014": ["band v-up", "waist"],
  "1015": ["band vertical pallof press", "waist"],
  "1016": ["band wrist curl", "lower arms"],
  "1017": ["band y-raise", "shoulders"],
  "0023": ["barbell alternate biceps curl", "upper arms"],
  "0024": ["barbell bench front squat", "upper legs"],
  "0025": ["barbell bench press", "chest"],
  "0026": ["barbell bench squat", "upper legs"],
  "1316": ["barbell bent arm pullover", "back"],
  "0027": ["barbell bent over row", "back"],
  "2407": ["barbell biceps curl (with arm blaster)", "upper arms"],
  "0028": ["barbell clean and press", "upper legs"],
  "0029": ["barbell clean-grip front squat", "upper legs"],
  "0030": ["barbell close-grip bench press", "upper arms"],
  "0031": ["barbell curl", "upper arms"],
  "0032": ["barbell deadlift", "upper legs"],
  "0033": ["barbell decline bench press", "chest"],
  "0034": ["barbell decline bent arm pullover", "back"],
  "0035": ["barbell decline close grip to skull press", "upper arms"],
  "1255": ["barbell decline pullover", "chest"],
  "0036": ["barbell decline wide-grip press", "chest"],
  "0037": ["barbell decline wide-grip pullover", "back"],
  "0038": ["barbell drag curl", "upper arms"],
  "1370": ["barbell floor calf raise", "lower legs"],
  "0039": ["barbell front chest squat", "upper legs"],
  "0041": ["barbell front raise", "shoulders"],
  "0040": ["barbell front raise and pullover", "chest"],
  "0042": ["barbell front squat", "upper legs"],
  "0043": ["barbell full squat", "upper legs"],
  "1461": ["barbell full squat (back pov)", "upper legs"],
  "1462": ["barbell full squat (side pov)", "upper legs"],
  "1545": ["barbell full zercher squat", "upper legs"],
  "1409": ["barbell glute bridge", "upper legs"],
  "3562": ["barbell glute bridge two legs on bench (male)", "upper legs"],
  "0044": ["barbell good morning", "upper legs"],
  "0045": ["barbell guillotine bench press", "chest"],
  "0046": ["barbell hack squat", "upper legs"],
  "1436": ["barbell high bar squat", "upper legs"],
  "0047": ["barbell incline bench press", "chest"],
  "1719": ["barbell incline close grip bench press", "upper arms"],
  "0048": ["barbell incline reverse-grip press", "upper arms"],
  "0049": ["barbell incline row", "back"],
  "0050": ["barbell incline shoulder raise", "chest"],
  "0051": ["barbell jefferson squat", "upper legs"],
  "0052": ["barbell jm bench press", "upper arms"],
  "0053": ["barbell jump squat", "upper legs"],
  "1410": ["barbell lateral lunge", "upper legs"],
  "1435": ["barbell low bar squat", "upper legs"],
  "0054": ["barbell lunge", "upper legs"],
  "1720": ["barbell lying back of the head tricep extension", "upper arms"],
  "0055": ["barbell lying close-grip press", "upper arms"],
  "0056": ["barbell lying close-grip triceps extension", "upper arms"],
  "0057": ["barbell lying extension", "upper arms"],
  "0058": ["barbell lying lifting (on hip)", "upper legs"],
  "0059": ["barbell lying preacher curl", "upper arms"],
  "0061": ["barbell lying triceps extension", "upper arms"],
  "0060": ["barbell lying triceps extension skull crusher", "upper arms"],
  "0063": ["barbell narrow stance squat", "upper legs"],
  "0064": ["barbell one arm bent over row", "back"],
  "0065": ["barbell one arm floor press", "upper arms"],
  "0066": ["barbell one arm side deadlift", "upper legs"],
  "0067": ["barbell one arm snatch", "shoulders"],
  "0068": ["barbell one leg squat", "upper legs"],
  "0069": ["barbell overhead squat", "upper legs"],
  "1411": ["barbell palms down wrist curl over a bench", "lower arms"],
  "1412": ["barbell palms up wrist curl over a bench", "lower arms"],
  "3017": ["barbell pendlay row", "back"],
  "1751": ["barbell pin presses", "upper arms"],
  "0070": ["barbell preacher curl", "upper arms"],
  "0071": ["barbell press sit-up", "waist"],
  "0072": ["barbell prone incline curl", "upper arms"],
  "0073": ["barbell pullover", "back"],
  "0022": ["barbell pullover to press", "back"],
  "0074": ["barbell rack pull", "upper legs"],
  "0075": ["barbell rear delt raise", "shoulders"],
  "0076": ["barbell rear delt row", "shoulders"],
  "0078": ["barbell rear lunge", "upper legs"],
  "0077": ["barbell rear lunge v. 2", "upper legs"],
  "0079": ["barbell revers wrist curl v. 2", "lower arms"],
  "2187": ["barbell reverse close-grip bench press", "upper arms"],
  "0080": ["barbell reverse curl", "upper arms"],
  "0118": ["barbell reverse grip bent over row", "back"],
  "1256": ["barbell reverse grip decline bench press", "chest"],
  "1257": ["barbell reverse grip incline bench press", "chest"],
  "1317": ["barbell reverse grip incline bench row", "back"],
  "1721": ["barbell reverse grip skullcrusher", "upper arms"],
  "0081": ["barbell reverse preacher curl", "upper arms"],
  "0082": ["barbell reverse wrist curl", "lower arms"],
  "0084": ["barbell rollerout", "waist"],
  "0083": ["barbell rollerout from bench", "waist"],
  "0085": ["barbell romanian deadlift", "upper legs"],
  "0086": ["barbell seated behind head military press", "shoulders"],
  "0087": ["barbell seated bradford rocky press", "shoulders"],
  "0088": ["barbell seated calf raise", "lower legs"],
  "1371": ["barbell seated calf raise", "lower legs"],
  "1718": ["barbell seated close grip behind neck triceps extension", "upper arms"],
  "0089": ["barbell seated close-grip concentration curl", "upper arms"],
  "0090": ["barbell seated good morning", "upper legs"],
  "0091": ["barbell seated overhead press", "shoulders"],
  "0092": ["barbell seated overhead triceps extension", "upper arms"],
  "0094": ["barbell seated twist", "waist"],
  "0095": ["barbell shrug", "back"],
  "0096": ["barbell side bent v. 2", "waist"],
  "0098": ["barbell side split squat", "upper legs"],
  "0097": ["barbell side split squat v. 2", "upper legs"],
  "1756": ["barbell single leg deadlift", "upper legs"],
  "0099": ["barbell single leg split squat", "upper legs"],
  "2799": ["barbell sitted alternate leg raise", "waist"],
  "2800": ["barbell sitted alternate leg raise (female)", "waist"],
  "0100": ["barbell skier", "shoulders"],
  "0101": ["barbell speed squat", "upper legs"],
  "2810": ["barbell split squat v. 2", "upper legs"],
  "0102": ["barbell squat (on knees)", "upper legs"],
  "2798": ["barbell squat jump step rear lunge", "upper legs"],
  "0103": ["barbell standing ab rollerout", "waist"],
  "0104": ["barbell standing back wrist curl", "lower arms"],
  "0105": ["barbell standing bradford press", "shoulders"],
  "1372": ["barbell standing calf raise", "lower legs"],
  "0106": ["barbell standing close grip curl", "upper arms"],
  "1456": ["barbell standing close grip military press", "shoulders"],
  "2414": ["barbell standing concentration curl", "upper arms"],
  "0107": ["barbell standing front raise over head", "shoulders"],
  "0108": ["barbell standing leg calf raise", "lower legs"],
  "0109": ["barbell standing overhead triceps extension", "upper arms"],
  "0110": ["barbell standing reverse grip curl", "upper arms"],
  "0111": ["barbell standing rocking leg calf raise", "lower legs"],
  "0112": ["barbell standing twist", "waist"],
  "1629": ["barbell standing wide grip biceps curl", "upper arms"],
  "1457": ["barbell standing wide military press", "shoulders"],
  "0113": ["barbell standing wide-grip curl", "upper arms"],
  "0114": ["barbell step-up", "upper legs"],
  "0115": ["barbell stiff leg good morning", "upper legs"],
  "0116": ["barbell straight leg deadlift", "upper legs"],
  "0117": ["barbell sumo deadlift", "upper legs"],
  "3305": ["barbell thruster", "shoulders"],
  "0120": ["barbell upright row", "shoulders"],
  "0119": ["barbell upright row v. 2", "shoulders"],
  "0121": ["barbell upright row v. 3", "shoulders"],
  "0122": ["barbell wide bench press", "chest"],
  "1258": ["barbell wide reverse grip bench press", "chest"],
  "0124": ["barbell wide squat", "upper legs"],
  "0123": ["barbell wide-grip upright row", "shoulders"],
  "0126": ["barbell wrist curl", "lower arms"],
  "0125": ["barbell wrist curl v. 2", "lower arms"],
  "0127": ["barbell zercher squat", "upper legs"],
  "3212": ["basic toe touch (male)", "upper legs"],
  "0128": ["battling ropes", "shoulders"],
  "3360": ["bear crawl", "cardio"],
  "1259": ["behind head chest stretch", "chest"],
  "0129": ["bench dip (knees bent)", "upper arms"],
  "1399": ["bench dip on floor", "upper arms"],
  "0130": ["bench hip extension", "upper legs"],
  "3019": ["bench pull-ups", "back"],
  "3639": ["bent knee lying twist (male)", "upper legs"],
  "1770": ["biceps leg concentration curl", "upper arms"],
  "0139": ["biceps narrow pull-ups", "upper arms"],
  "0140": ["biceps pull-up", "upper arms"],
  "0137": ["body-up", "upper arms"],
  "3543": ["bodyweight drop jump squat", "upper legs"],
  "3544": ["bodyweight incline side plank", "waist"],
  "1771": ["bodyweight kneeling triceps extension", "upper arms"],
  "1769": ["bodyweight side lying biceps curl", "upper arms"],
  "3168": ["bodyweight squatting row", "back"],
  "3167": ["bodyweight squatting row (with towel)", "back"],
  "1373": ["bodyweight standing calf raise", "lower legs"],
  "3156": ["bodyweight standing close-grip one arm row", "back"],
  "3158": ["bodyweight standing close-grip row", "back"],
  "3162": ["bodyweight standing one arm row", "back"],
  "3161": ["bodyweight standing one arm row (with towel)", "back"],
  "3166": ["bodyweight standing row", "back"],
  "3165": ["bodyweight standing row (with towel)", "back"],
  "0138": ["bottoms-up", "waist"],
  "1374": ["box jump down with one leg stabilization", "lower legs"],
  "2466": ["bridge - mountain climber (cross body)", "waist"],
  "1160": ["burpee", "cardio"],
  "0870": ["butt-ups", "waist"],
  "1494": ["butterfly yoga pose", "upper legs"],
  "0148": ["cable alternate shoulder press", "shoulders"],
  "0149": ["cable alternate triceps extension", "upper arms"],
  "3235": ["cable assisted inverse leg curl", "upper legs"],
  "0150": ["cable bar lateral pulldown", "back"],
  "0151": ["cable bench press", "chest"],
  "1630": ["cable close grip curl", "upper arms"],
  "1631": ["cable concentration curl", "upper arms"],
  "0152": ["cable concentration extension (on knee)", "upper arms"],
  "0153": ["cable cross-over lateral pulldown", "back"],
  "0154": ["cable cross-over revers fly", "shoulders"],
  "0155": ["cable cross-over variation", "chest"],
  "0868": ["cable curl", "upper arms"],
  "0157": ["cable deadlift", "upper legs"],
  "0158": ["cable decline fly", "chest"],
  "1260": ["cable decline one arm press", "chest"],
  "1261": ["cable decline press", "chest"],
  "0159": ["cable decline seated wide-grip row", "back"],
  "1632": ["cable drag curl", "upper arms"],
  "0160": ["cable floor seated wide-grip row", "back"],
  "0161": ["cable forward raise", "shoulders"],
  "0162": ["cable front raise", "shoulders"],
  "0164": ["cable front shoulder raise", "shoulders"],
  "0165": ["cable hammer curl (with rope)", "upper arms"],
  "1722": ["cable high pulley overhead tricep extension", "upper arms"],
  "0167": ["cable high row (kneeling)", "back"],
  "0168": ["cable hip adduction", "upper legs"],
  "0169": ["cable incline bench press", "chest"],
  "1318": ["cable incline bench row", "back"],
  "0171": ["cable incline fly", "chest"],
  "0170": ["cable incline fly (on stability ball)", "chest"],
  "0172": ["cable incline pushdown", "back"],
  "0173": ["cable incline triceps extension", "upper arms"],
  "0174": ["cable judo flip", "waist"],
  "0860": ["cable kickback", "upper arms"],
  "0175": ["cable kneeling crunch", "waist"],
  "3697": ["cable kneeling rear delt row (with rope) (male)", "shoulders"],
  "0176": ["cable kneeling triceps extension", "upper arms"],
  "2330": ["cable lat pulldown full range of motion", "back"],
  "0177": ["cable lateral pulldown (with rope attachment)", "back"],
  "2616": ["cable lateral pulldown with v-bar", "back"],
  "0178": ["cable lateral raise", "shoulders"],
  "0179": ["cable low fly", "chest"],
  "0180": ["cable low seated row", "back"],
  "1634": ["cable lying bicep curl", "upper arms"],
  "0182": ["cable lying close-grip curl", "upper arms"],
  "0184": ["cable lying extension pullover (with rope attachment)", "back"],
  "0185": ["cable lying fly", "chest"],
  "0186": ["cable lying triceps extension v. 2", "upper arms"],
  "0188": ["cable middle fly", "chest"],
  "0189": ["cable one arm bent over row", "back"],
  "0190": ["cable one arm curl", "upper arms"],
  "1262": ["cable one arm decline chest fly", "chest"],
  "1263": ["cable one arm fly on exercise ball", "chest"],
  "1264": ["cable one arm incline fly on exercise ball", "chest"],
  "1265": ["cable one arm incline press", "chest"],
  "1266": ["cable one arm incline press on exercise ball", "chest"],
  "0191": ["cable one arm lateral bent-over", "chest"],
  "0192": ["cable one arm lateral raise", "shoulders"],
  "1633": ["cable one arm preacher curl", "upper arms"],
  "1267": ["cable one arm press on exercise ball", "chest"],
  "3563": ["cable one arm pulldown", "back"],
  "1635": ["cable one arm reverse preacher curl", "upper arms"],
  "0193": ["cable one arm straight back high row (kneeling)", "back"],
  "1723": ["cable one arm tricep pushdown", "upper arms"],
  "1636": ["cable overhead curl", "upper arms"],
  "1637": ["cable overhead curl on exercise ball", "upper arms"],
  "0194": ["cable overhead triceps extension (rope attachment)", "upper arms"],
  "1319": ["cable palm rotational row", "back"],
  "0195": ["cable preacher curl", "upper arms"],
  "1268": ["cable press on exercise ball", "chest"],
  "0196": ["cable pull through (with rope)", "upper legs"],
  "0198": ["cable pulldown", "back"],
  "0197": ["cable pulldown (pro lat bar)", "back"],
  "1638": ["cable pulldown bicep curl", "upper arms"],
  "0201": ["cable pushdown", "upper arms"],
  "0199": ["cable pushdown (straight arm) v. 2", "back"],
  "0200": ["cable pushdown (with rope attachment)", "upper arms"],
  "0202": ["cable rear delt row (stirrups)", "shoulders"],
  "0203": ["cable rear delt row (with rope)", "shoulders"],
  "0204": ["cable rear drive", "upper arms"],
  "0205": ["cable rear pulldown", "back"],
  "0873": ["cable reverse crunch", "waist"],
  "0206": ["cable reverse curl", "upper arms"],
  "2406": ["cable reverse grip triceps pushdown (sz-bar) (with arm blaster)", "upper arms"],
  "1413": ["cable reverse one arm curl", "upper arms"],
  "0209": ["cable reverse preacher curl", "upper arms"],
  "0210": ["cable reverse wrist curl", "lower arms"],
  "0207": ["cable reverse-grip pushdown", "upper arms"],
  "0208": ["cable reverse-grip straight back seated high row", "back"],
  "1320": ["cable rope crossover seated row", "back"],
  "1321": ["cable rope elevated seated row", "back"],
  "1322": ["cable rope extension incline bench row", "back"],
  "1639": ["cable rope hammer preacher curl", "upper arms"],
  "1724": ["cable rope high pulley overhead tricep extension", "upper arms"],
  "1725": ["cable rope incline tricep extension", "upper arms"],
  "1726": ["cable rope lying on floor tricep extension", "upper arms"],
  "1640": ["cable rope one arm hammer preacher curl", "upper arms"],
  "1323": ["cable rope seated row", "back"],
  "0211": ["cable russian twists (on stability ball)", "waist"],
  "2144": ["cable seated chest press", "chest"],
  "0212": ["cable seated crunch", "waist"],
  "1641": ["cable seated curl", "upper arms"],
  "0213": ["cable seated high row (v-bar)", "back"],
  "0214": ["cable seated one arm alternate row", "back"],
  "1642": ["cable seated one arm concentration curl", "upper arms"],
  "1643": ["cable seated overhead curl", "upper arms"],
  "0215": ["cable seated rear lateral raise", "shoulders"],
  "0861": ["cable seated row", "back"],
  "0216": ["cable seated shoulder internal rotation", "shoulders"],
  "2399": ["cable seated twist", "waist"],
  "0218": ["cable seated wide-grip row", "back"],
  "0219": ["cable shoulder press", "shoulders"],
  "0220": ["cable shrug", "back"],
  "0222": ["cable side bend", "waist"],
  "0221": ["cable side bend crunch (bosu ball)", "waist"],
  "0223": ["cable side crunch", "waist"],
  "1717": ["cable squat row (with rope attachment)", "back"],
  "1644": ["cable squatting curl", "upper arms"],
  "0224": ["cable standing back wrist curl", "lower arms"],
  "1375": ["cable standing calf raise", "lower legs"],
  "0225": ["cable standing cross-over high reverse fly", "shoulders"],
  "0226": ["cable standing crunch", "waist"],
  "0874": ["cable standing crunch (with rope attachment)", "waist"],
  "0227": ["cable standing fly", "chest"],
  "0228": ["cable standing hip extension", "upper legs"],
  "0229": ["cable standing inner curl", "upper arms"],
  "0230": ["cable standing lift", "waist"],
  "0231": ["cable standing one arm triceps extension", "upper arms"],
  "1376": ["cable standing one leg calf raise", "lower legs"],
  "0232": ["cable standing pulldown (with rope)", "upper arms"],
  "0233": ["cable standing rear delt row (with rope)", "shoulders"],
  "1727": ["cable standing reverse grip one arm overhead tricep extension", "upper arms"],
  "0234": ["cable standing row (v-bar)", "back"],
  "0235": ["cable standing shoulder external rotation", "shoulders"],
  "0236": ["cable standing twist row (v-bar)", "back"],
  "1269": ["cable standing up straight crossovers", "chest"],
  "0238": ["cable straight arm pulldown", "back"],
  "0237": ["cable straight arm pulldown (with rope)", "back"],
  "0239": ["cable straight back seated row", "back"],
  "0240": ["cable supine reverse fly", "shoulders"],
  "2464": ["cable thibaudeau kayak row", "back"],
  "0241": ["cable triceps pushdown (v-bar)", "upper arms"],
  "2405": ["cable triceps pushdown (v-bar) (with arm blaster)", "upper arms"],
  "0242": ["cable tuck reverse crunch", "waist"],
  "0243": ["cable twist", "waist"],
  "0862": ["cable twist (up-down)", "waist"],
  "0244": ["cable twisting pull", "back"],
  "1645": ["cable two arm curl on incline bench", "upper arms"],
  "1728": ["cable two arm tricep kickback", "upper arms"],
  "0245": ["cable underhand pulldown", "back"],
  "1270": ["cable upper chest crossovers", "chest"],
  "1324": ["cable upper row", "back"],
  "0246": ["cable upright row", "shoulders"],
  "1325": ["cable wide grip rear pulldown behind neck", "back"],
  "0247": ["cable wrist curl", "lower arms"],
  "1407": ["calf push stretch with hands against wall", "lower legs"],
  "1377": ["calf stretch with hands against wall", "lower legs"],
  "1378": ["calf stretch with rope", "lower legs"],
  "0248": ["cambered bar lying row", "back"],
  "2963": ["captains chair straight leg raise", "waist"],
  "1548": ["chair leg extended stretch", "upper legs"],
  "1271": ["chest and front of shoulder stretch", "chest"],
  "0251": ["chest dip", "chest"],
  "1430": ["chest dip (on dip-pull-up cage)", "chest"],
  "2462": ["chest dip on straight bar", "chest"],
  "1272": ["chest stretch with exercise ball", "chest"],
  "3216": ["chest tap push-up (male)", "chest"],
  "1326": ["chin-up", "back"],
  "0253": ["chin-ups (narrow parallel grip)", "back"],
  "0257": ["circles knee stretch", "lower legs"],
  "1273": ["clap push up", "chest"],
  "0258": ["clock push-up", "chest"],
  "1327": ["close grip chin-up", "back"],
  "0259": ["close-grip push-up", "upper arms"],
  "2398": ["close-grip push-up (on knees)", "upper arms"],
  "0260": ["cocoons", "waist"],
  "1468": ["crab twist toe touch", "waist"],
  "0262": ["cross body crunch", "waist"],
  "0267": ["crunch (hands overhead)", "waist"],
  "0271": ["crunch (on stability ball)", "waist"],
  "0272": ["crunch (on stability ball, arms straight)", "waist"],
  "0274": ["crunch floor", "waist"],
  "3016": ["curl-up", "waist"],
  "3769": ["curtsey squat", "upper legs"],
  "2331": ["cycle cross trainer", "cardio"],
  "0276": ["dead bug", "waist"],
  "0277": ["decline crunch", "waist"],
  "0279": ["decline push-up", "chest"],
  "0282": ["decline sit-up", "waist"],
  "1274": ["deep push up", "chest"],
  "0283": ["diamond push-up", "upper arms"],
  "0284": ["donkey calf raise", "lower legs"],
  "1275": ["drop push up", "chest"],
  "0285": ["dumbbell alternate biceps curl", "upper arms"],
  "2403": ["dumbbell alternate biceps curl (with arm blaster)", "upper arms"],
  "1646": ["dumbbell alternate hammer preacher curl", "upper arms"],
  "1647": ["dumbbell alternate preacher curl", "upper arms"],
  "1648": ["dumbbell alternate seated hammer curl", "upper arms"],
  "0286": ["dumbbell alternate side press", "shoulders"],
  "1649": ["dumbbell alternating bicep curl with leg raised on exercise ball", "upper arms"],
  "1650": ["dumbbell alternating seated bicep curl on exercise ball", "upper arms"],
  "2137": ["dumbbell arnold press", "shoulders"],
  "0287": ["dumbbell arnold press v. 2", "shoulders"],
  "0288": ["dumbbell around pullover", "chest"],
  "0289": ["dumbbell bench press", "chest"],
  "0290": ["dumbbell bench seated press", "shoulders"],
  "0291": ["dumbbell bench squat", "upper legs"],
  "0293": ["dumbbell bent over row", "back"],
  "1651": ["dumbbell bicep curl lunge with bowling motion", "upper arms"],
  "1652": ["dumbbell bicep curl on exercise ball with leg raised", "upper arms"],
  "1653": ["dumbbell bicep curl with stork stance", "upper arms"],
  "0294": ["dumbbell biceps curl", "upper arms"],
  "2401": ["dumbbell biceps curl (with arm blaster)", "upper arms"],
  "1654": ["dumbbell biceps curl reverse", "upper arms"],
  "1655": ["dumbbell biceps curl squat", "upper arms"],
  "1656": ["dumbbell biceps curl v sit on bosu ball", "upper arms"],
  "1201": ["dumbbell burpee", "cardio"],
  "0295": ["dumbbell clean", "upper legs"],
  "1731": ["dumbbell close grip press", "upper arms"],
  "0296": ["dumbbell close-grip press", "upper arms"],
  "0297": ["dumbbell concentration curl", "upper arms"],
  "3635": ["dumbbell contralateral forward lunge", "upper legs"],
  "0298": ["dumbbell cross body hammer curl", "upper arms"],
  "1657": ["dumbbell cross body hammer curl v. 2", "upper arms"],
  "0299": ["dumbbell cuban press", "shoulders"],
  "2136": ["dumbbell cuban press v. 2", "shoulders"],
  "0300": ["dumbbell deadlift", "upper legs"],
  "0301": ["dumbbell decline bench press", "chest"],
  "0302": ["dumbbell decline fly", "chest"],
  "0303": ["dumbbell decline hammer press", "chest"],
  "1276": ["dumbbell decline one arm fly", "chest"],
  "1617": ["dumbbell decline one arm hammer press", "upper arms"],
  "0305": ["dumbbell decline shrug", "back"],
  "0304": ["dumbbell decline shrug v. 2", "back"],
  "0306": ["dumbbell decline triceps extension", "upper arms"],
  "0307": ["dumbbell decline twist fly", "chest"],
  "1437": ["dumbbell finger curls", "lower arms"],
  "0308": ["dumbbell fly", "chest"],
  "1277": ["dumbbell fly on exercise ball", "chest"],
  "1732": ["dumbbell forward lunge triceps extension", "upper arms"],
  "0310": ["dumbbell front raise", "shoulders"],
  "0309": ["dumbbell front raise v. 2", "shoulders"],
  "0311": ["dumbbell full can lateral raise", "shoulders"],
  "1760": ["dumbbell goblet squat", "upper legs"],
  "0313": ["dumbbell hammer curl", "upper arms"],
  "1659": ["dumbbell hammer curl on exercise ball", "upper arms"],
  "0312": ["dumbbell hammer curl v. 2", "upper arms"],
  "2402": ["dumbbell hammer curls (with arm blaster)", "upper arms"],
  "1664": ["dumbbell high curl", "upper arms"],
  "3545": ["dumbbell incline alternate press", "chest"],
  "0314": ["dumbbell incline bench press", "chest"],
  "0315": ["dumbbell incline biceps curl", "upper arms"],
  "0316": ["dumbbell incline breeding", "chest"],
  "0318": ["dumbbell incline curl", "upper arms"],
  "0317": ["dumbbell incline curl v. 2", "upper arms"],
  "0319": ["dumbbell incline fly", "chest"],
  "1278": ["dumbbell incline fly on exercise ball", "chest"],
  "0320": ["dumbbell incline hammer curl", "upper arms"],
  "0321": ["dumbbell incline hammer press", "chest"],
  "1618": ["dumbbell incline hammer press on exercise ball", "upper arms"],
  "0322": ["dumbbell incline inner biceps curl", "upper arms"],
  "1279": ["dumbbell incline one arm fly", "chest"],
  "1280": ["dumbbell incline one arm fly on exercise ball", "chest"],
  "1619": ["dumbbell incline one arm hammer press", "upper arms"],
  "1620": ["dumbbell incline one arm hammer press on exercise ball", "upper arms"],
  "0323": ["dumbbell incline one arm lateral raise", "shoulders"],
  "1281": ["dumbbell incline one arm press", "chest"],
  "1282": ["dumbbell incline one arm press on exercise ball", "chest"],
  "0324": ["dumbbell incline palm-in press", "chest"],
  "1283": ["dumbbell incline press on exercise ball", "chest"],
  "0325": ["dumbbell incline raise", "shoulders"],
  "0326": ["dumbbell incline rear lateral raise", "shoulders"],
  "0327": ["dumbbell incline row", "back"],
  "0328": ["dumbbell incline shoulder raise", "chest"],
  "0329": ["dumbbell incline shrug", "back"],
  "3542": ["dumbbell incline t-raise", "shoulders"],
  "0330": ["dumbbell incline triceps extension", "upper arms"],
  "0331": ["dumbbell incline twisted flyes", "chest"],
  "1733": ["dumbbell incline two arm extension", "upper arms"],
  "3541": ["dumbbell incline y-raise", "back"],
  "0332": ["dumbbell iron cross", "shoulders"],
  "0333": ["dumbbell kickback", "upper arms"],
  "1734": ["dumbbell kickbacks on exercise ball", "upper arms"],
  "1660": ["dumbbell kneeling bicep curl exercise ball", "upper arms"],
  "0334": ["dumbbell lateral raise", "shoulders"],
  "0335": ["dumbbell lateral to front raise", "shoulders"],
  "0336": ["dumbbell lunge", "upper legs"],
  "1658": ["dumbbell lunge with bicep curl", "upper arms"],
  "0337": ["dumbbell lying extension (across face)", "upper arms"],
  "1729": ["dumbbell lying alternate extension", "upper arms"],
  "0338": ["dumbbell lying elbow press", "upper arms"],
  "0863": ["dumbbell lying external shoulder rotation", "shoulders"],
  "0339": ["dumbbell lying femoral", "upper legs"],
  "0340": ["dumbbell lying hammer press", "chest"],
  "2470": ["dumbbell lying on floor rear delt raise", "shoulders"],
  "0341": ["dumbbell lying one arm deltoid rear", "shoulders"],
  "0343": ["dumbbell lying one arm press", "chest"],
  "0342": ["dumbbell lying one arm press v. 2", "chest"],
  "0344": ["dumbbell lying one arm pronated triceps extension", "upper arms"],
  "0345": ["dumbbell lying one arm rear lateral raise", "shoulders"],
  "0346": ["dumbbell lying one arm supinated triceps extension", "upper arms"],
  "0347": ["dumbbell lying pronation", "lower arms"],
  "2705": ["dumbbell lying pronation on floor", "lower arms"],
  "1284": ["dumbbell lying pullover on exercise ball", "chest"],
  "1328": ["dumbbell lying rear delt row", "back"],
  "0348": ["dumbbell lying rear lateral raise", "shoulders"],
  "1735": ["dumbbell lying single extension", "upper arms"],
  "0349": ["dumbbell lying supination", "lower arms"],
  "2706": ["dumbbell lying supination on floor", "lower arms"],
  "1661": ["dumbbell lying supine biceps curl", "upper arms"],
  "0350": ["dumbbell lying supine curl", "upper arms"],
  "0351": ["dumbbell lying triceps extension", "upper arms"],
  "1662": ["dumbbell lying wide curl", "upper arms"],
  "0352": ["dumbbell neutral grip bench press", "upper arms"],
  "1285": ["dumbbell one arm bench fly", "chest"],
  "0292": ["dumbbell one arm bent-over row", "back"],
  "1286": ["dumbbell one arm chest fly on exercise ball", "chest"],
  "0353": ["dumbbell one arm concentration curl (on stability ball)", "upper arms"],
  "1287": ["dumbbell one arm decline chest press", "chest"],
  "1288": ["dumbbell one arm fly on exercise ball", "chest"],
  "1736": ["dumbbell one arm french press on exercise ball", "upper arms"],
  "1663": ["dumbbell one arm hammer preacher curl", "upper arms"],
  "1621": ["dumbbell one arm hammer press on exercise ball", "upper arms"],
  "1289": ["dumbbell one arm incline chest press", "chest"],
  "0354": ["dumbbell one arm kickback", "upper arms"],
  "0355": ["dumbbell one arm lateral raise", "shoulders"],
  "0356": ["dumbbell one arm lateral raise with support", "shoulders"],
  "1290": ["dumbbell one arm press on exercise ball", "chest"],
  "1665": ["dumbbell one arm prone curl", "upper arms"],
  "1666": ["dumbbell one arm prone hammer curl", "upper arms"],
  "1291": ["dumbbell one arm pullover on exercise ball", "chest"],
  "0358": ["dumbbell one arm reverse wrist curl", "lower arms"],
  "0359": ["dumbbell one arm reverse fly (with support)", "shoulders"],
  "1622": ["dumbbell one arm reverse grip press", "chest"],
  "1414": ["dumbbell one arm reverse preacher curl", "upper arms"],
  "1667": ["dumbbell one arm reverse spider curl", "upper arms"],
  "1668": ["dumbbell one arm seated bicep curl on exercise ball", "upper arms"],
  "1669": ["dumbbell one arm seated hammer curl", "upper arms"],
  "1415": ["dumbbell one arm seated neutral wrist curl", "lower arms"],
  "0361": ["dumbbell one arm shoulder press", "shoulders"],
  "0360": ["dumbbell one arm shoulder press v. 2", "shoulders"],
  "3888": ["dumbbell one arm snatch", "upper legs"],
  "1670": ["dumbbell one arm standing curl", "upper arms"],
  "1671": ["dumbbell one arm standing hammer curl", "upper arms"],
  "0362": ["dumbbell one arm triceps extension (on bench)", "upper arms"],
  "0363": ["dumbbell one arm upright row", "shoulders"],
  "0364": ["dumbbell one arm wrist curl", "lower arms"],
  "1672": ["dumbbell one arm zottman preacher curl", "upper arms"],
  "1292": ["dumbbell one leg fly on exercise ball", "chest"],
  "0365": ["dumbbell over bench neutral wrist curl", "upper arms"],
  "0366": ["dumbbell over bench one arm neutral wrist curl", "upper arms"],
  "1441": ["dumbbell over bench one arm reverse wrist curl", "lower arms"],
  "0367": ["dumbbell over bench one arm wrist curl", "lower arms"],
  "0368": ["dumbbell over bench revers wrist curl", "lower arms"],
  "0369": ["dumbbell over bench wrist curl", "lower arms"],
  "1329": ["dumbbell palm rotational bent over row", "back"],
  "1623": ["dumbbell palms in incline bench press", "upper arms"],
  "0370": ["dumbbell peacher hammer curl", "upper arms"],
  "0371": ["dumbbell plyo squat", "upper legs"],
  "0372": ["dumbbell preacher curl", "upper arms"],
  "1673": ["dumbbell preacher curl over exercise ball", "upper arms"],
  "1293": ["dumbbell press on exercise ball", "chest"],
  "0373": ["dumbbell pronate-grip triceps extension", "upper arms"],
  "0374": ["dumbbell prone incline curl", "upper arms"],
  "1674": ["dumbbell prone incline hammer curl", "upper arms"],
  "0375": ["dumbbell pullover", "chest"],
  "1294": ["dumbbell pullover hip extension on exercise ball", "chest"],
  "1295": ["dumbbell pullover on exercise ball", "chest"],
  "1700": ["dumbbell push press", "shoulders"],
  "0376": ["dumbbell raise", "shoulders"],
  "2292": ["dumbbell rear delt raise", "shoulders"],
  "0377": ["dumbbell rear delt row_shoulder", "shoulders"],
  "0378": ["dumbbell rear fly", "shoulders"],
  "0380": ["dumbbell rear lateral raise", "shoulders"],
  "0379": ["dumbbell rear lateral raise (support head)", "shoulders"],
  "0381": ["dumbbell rear lunge", "upper legs"],
  "0382": ["dumbbell revers grip biceps curl", "upper arms"],
  "1624": ["dumbbell reverse bench press", "chest"],
  "0383": ["dumbbell reverse fly", "shoulders"],
  "1330": ["dumbbell reverse grip incline bench one arm row", "back"],
  "1331": ["dumbbell reverse grip incline bench two arm row", "back"],
  "2327": ["dumbbell reverse grip row (female)", "back"],
  "0384": ["dumbbell reverse preacher curl", "upper arms"],
  "1675": ["dumbbell reverse spider curl", "upper arms"],
  "0385": ["dumbbell reverse wrist curl", "lower arms"],
  "1459": ["dumbbell romanian deadlift", "upper legs"],
  "0386": ["dumbbell rotation reverse fly", "shoulders"],
  "2397": ["dumbbell scott press", "shoulders"],
  "0387": ["dumbbell seated alternate front raise", "shoulders"],
  "1676": ["dumbbell seated alternate hammer curl on exercise ball", "upper arms"],
  "0388": ["dumbbell seated alternate press", "shoulders"],
  "3546": ["dumbbell seated alternate shoulder", "shoulders"],
  "0389": ["dumbbell seated bench extension", "upper arms"],
  "2317": ["dumbbell seated bent arm lateral raise", "shoulders"],
  "1730": ["dumbbell seated bent over alternate kickback", "upper arms"],
  "1737": ["dumbbell seated bent over triceps extension", "upper arms"],
  "1677": ["dumbbell seated bicep curl", "upper arms"],
  "0390": ["dumbbell seated biceps curl (on stability ball)", "upper arms"],
  "3547": ["dumbbell seated biceps curl to shoulder press", "upper arms"],
  "1379": ["dumbbell seated calf raise", "lower legs"],
  "0391": ["dumbbell seated curl", "upper arms"],
  "0392": ["dumbbell seated front raise", "shoulders"],
  "1678": ["dumbbell seated hammer curl", "upper arms"],
  "0393": ["dumbbell seated inner biceps curl", "upper arms"],
  "0394": ["dumbbell seated kickback", "upper arms"],
  "0396": ["dumbbell seated lateral raise", "shoulders"],
  "0395": ["dumbbell seated lateral raise v. 2", "shoulders"],
  "0397": ["dumbbell seated neutral wrist curl", "upper arms"],
  "1679": ["dumbbell seated one arm bicep curl on exercise ball with leg raised", "upper arms"],
  "0398": ["dumbbell seated one arm kickback", "upper arms"],
  "0399": ["dumbbell seated one arm rotate", "lower arms"],
  "0400": ["dumbbell seated one leg calf raise", "lower legs"],
  "1380": ["dumbbell seated one leg calf raise - hammer grip", "lower legs"],
  "1381": ["dumbbell seated one leg calf raise - palm up", "lower legs"],
  "0401": ["dumbbell seated palms up wrist curl", "lower arms"],
  "0402": ["dumbbell seated preacher curl", "upper arms"],
  "0403": ["dumbbell seated revers grip concentration curl", "upper arms"],
  "1738": ["dumbbell seated reverse grip one arm overhead tricep extension", "upper arms"],
  "0405": ["dumbbell seated shoulder press", "shoulders"],
  "0404": ["dumbbell seated shoulder press (parallel grip)", "shoulders"],
  "2188": ["dumbbell seated triceps extension", "upper arms"],
  "0406": ["dumbbell shrug", "back"],
  "0407": ["dumbbell side bend", "waist"],
  "0408": ["dumbbell side lying one hand raise", "shoulders"],
  "3664": ["dumbbell side plank with rear fly", "back"],
  "3548": ["dumbbell single arm overhead carry", "shoulders"],
  "0409": ["dumbbell single leg calf raise", "lower legs"],
  "1757": ["dumbbell single leg deadlift", "upper legs"],
  "2805": ["dumbbell single leg deadlift with stepbox support", "upper legs"],
  "0410": ["dumbbell single leg split squat", "upper legs"],
  "0411": ["dumbbell single leg squat", "upper legs"],
  "0413": ["dumbbell squat", "upper legs"],
  "3560": ["dumbbell standing alternate hammer curl and press", "upper arms"],
  "0414": ["dumbbell standing alternate overhead press", "shoulders"],
  "0415": ["dumbbell standing alternate raise", "shoulders"],
  "1739": ["dumbbell standing alternating tricep kickback", "upper arms"],
  "2143": ["dumbbell standing around world", "shoulders"],
  "1740": ["dumbbell standing bent over one arm triceps extension", "upper arms"],
  "1741": ["dumbbell standing bent over two arm triceps extension", "upper arms"],
  "0416": ["dumbbell standing biceps curl", "upper arms"],
  "0417": ["dumbbell standing calf raise", "lower legs"],
  "0418": ["dumbbell standing concentration curl", "upper arms"],
  "0419": ["dumbbell standing front raise above head", "shoulders"],
  "2321": ["dumbbell standing inner biceps curl v. 2", "upper arms"],
  "0420": ["dumbbell standing kickback", "upper arms"],
  "0421": ["dumbbell standing one arm concentration curl", "upper arms"],
  "0422": ["dumbbell standing one arm curl (over incline bench)", "upper arms"],
  "1680": ["dumbbell standing one arm curl over incline bench", "upper arms"],
  "0423": ["dumbbell standing one arm extension", "upper arms"],
  "0424": ["dumbbell standing one arm palm in press", "shoulders"],
  "0425": ["dumbbell standing one arm reverse curl", "upper arms"],
  "0426": ["dumbbell standing overhead press", "shoulders"],
  "0427": ["dumbbell standing palms in press", "shoulders"],
  "0428": ["dumbbell standing preacher curl", "upper arms"],
  "0429": ["dumbbell standing reverse curl", "upper arms"],
  "0430": ["dumbbell standing triceps extension", "upper arms"],
  "2293": ["dumbbell standing zottman preacher curl", "upper arms"],
  "1684": ["dumbbell step up single leg balance with bicep curl", "upper arms"],
  "0431": ["dumbbell step-up", "upper legs"],
  "2796": ["dumbbell step-up lunge", "upper legs"],
  "2812": ["dumbbell step-up split squat", "upper legs"],
  "0432": ["dumbbell stiff leg deadlift", "upper legs"],
  "0433": ["dumbbell straight arm pullover", "chest"],
  "0434": ["dumbbell straight leg deadlift", "upper legs"],
  "2808": ["dumbbell sumo pull through", "upper legs"],
  "2803": ["dumbbell supported squat", "upper legs"],
  "0436": ["dumbbell tate press", "upper arms"],
  "1742": ["dumbbell tricep kickback with stork stance", "upper arms"],
  "1743": ["dumbbell twisting bench press", "upper arms"],
  "0437": ["dumbbell upright row", "shoulders"],
  "1765": ["dumbbell upright row (back pov)", "shoulders"],
  "0864": ["dumbbell upright shoulder external rotation", "shoulders"],
  "5201": ["dumbbell waiter biceps curl", "upper arms"],
  "0438": ["dumbbell w-press", "shoulders"],
  "0439": ["dumbbell zottman curl", "upper arms"],
  "2294": ["dumbbell zottman preacher curl", "upper arms"],
  "2189": ["dumbbells seated triceps extension", "upper arms"],
  "1167": ["dynamic chest stretch (male)", "chest"],
  "3287": ["elbow dips", "upper arms"],
  "1772": ["elbow lift - reverse push-up", "back"],
  "0443": ["elbow-to-knee", "waist"],
  "3292": ["elevator", "back"],
  "1332": ["exercise ball alternating arm ups", "back"],
  "1333": ["exercise ball back extension with arms extended", "back"],
  "1334": ["exercise ball back extension with hands behind head", "back"],
  "1335": ["exercise ball back extension with knees off ground", "back"],
  "1336": ["exercise ball back extension with rotation", "back"],
  "1744": ["exercise ball dip", "upper arms"],
  "1559": ["exercise ball hip flexor stretch", "upper legs"],
  "1338": ["exercise ball hug", "back"],
  "1339": ["exercise ball lat stretch", "back"],
  "1341": ["exercise ball lower back stretch (pyramid)", "back"],
  "1342": ["exercise ball lying side lat stretch", "back"],
  "1382": ["exercise ball on the wall calf raise", "lower legs"],
  "3241": ["exercise ball on the wall calf raise (tennis ball between ankles)", "lower legs"],
  "3240": ["exercise ball on the wall calf raise (tennis ball between knees)", "lower legs"],
  "1416": ["exercise ball one leg prone lower body rotation", "upper legs"],
  "1417": ["exercise ball one legged diagonal kick hamstring curl", "upper legs"],
  "1296": ["exercise ball pike push up", "chest"],
  "1343": ["exercise ball prone leg raise", "back"],
  "1560": ["exercise ball seated hamstring stretch", "upper legs"],
  "1745": ["exercise ball seated triceps stretch", "upper arms"],
  "1746": ["exercise ball supine triceps extension", "upper arms"],
  "1747": ["ez bar french press on exercise ball", "upper arms"],
  "3010": ["ez bar lying bent arms pullover", "back"],
  "1748": ["ez bar lying close grip triceps extension behind head", "upper arms"],
  "1344": ["ez bar reverse grip bent over row", "back"],
  "1682": ["ez bar seated close grip concentration curl", "upper arms"],
  "1749": ["ez bar standing french press", "upper arms"],
  "0445": ["ez barbell anti gravity press", "shoulders"],
  "1627": ["ez barbell close grip preacher curl", "upper arms"],
  "0446": ["ez barbell close-grip curl", "upper arms"],
  "0447": ["ez barbell curl", "upper arms"],
  "0448": ["ez barbell decline close grip face press", "upper arms"],
  "2186": ["ez barbell decline triceps extension", "upper arms"],
  "0449": ["ez barbell incline triceps extension", "upper arms"],
  "0450": ["ez barbell jm bench press", "upper arms"],
  "0451": ["ez barbell reverse grip curl", "upper arms"],
  "0452": ["ez barbell reverse grip preacher curl", "upper arms"],
  "1458": ["ez barbell seated curls", "upper arms"],
  "0453": ["ez barbell seated triceps extension", "upper arms"],
  "0454": ["ez barbell spider curl", "upper arms"],
  "1628": ["ez barbell spider curl", "upper arms"],
  "2404": ["ez-bar biceps curl (with arm blaster)", "upper arms"],
  "2432": ["ez-bar close-grip bench press", "upper arms"],
  "2741": ["ez-barbell standing wide grip biceps curl", "upper arms"],
  "2133": ["farmers walk", "upper legs"],
  "0455": ["finger curls", "lower arms"],
  "3303": ["flag", "waist"],
  "0456": ["flexion leg sit up (bent knee)", "waist"],
  "0457": ["flexion leg sit up (straight arm)", "waist"],
  "0458": ["floor fly (with barbell)", "chest"],
  "0459": ["flutter kicks", "upper legs"],
  "1472": ["forward jump", "upper legs"],
  "3470": ["forward lunge (male)", "upper legs"],
  "3194": ["frankenstein squat", "upper legs"],
  "2429": ["frog crunch", "waist"],
  "3301": ["frog planche", "waist"],
  "3296": ["front lever", "waist"],
  "3295": ["front lever reps", "back"],
  "0464": ["front plank with twist", "waist"],
  "3315": ["full maltese", "waist"],
  "3299": ["full planche", "waist"],
  "3327": ["full planche push-up", "chest"],
  "0466": ["gironda sternum chin", "back"],
  "3561": ["glute bridge march", "upper legs"],
  "3523": ["glute bridge two legs on bench (male)", "upper legs"],
  "3193": ["glute-ham raise", "upper legs"],
  "0467": ["gorilla chin", "waist"],
  "0469": ["groin crunch", "waist"],
  "1383": ["hack calf raise", "lower legs"],
  "1384": ["hack one leg calf raise", "lower legs"],
  "3221": ["half knee bends (male)", "cardio"],
  "3202": ["half sit-up (male)", "waist"],
  "1511": ["hamstring stretch", "upper legs"],
  "2139": ["hands bike", "chest"],
  "3218": ["hands clasped circular toe touch (male)", "upper legs"],
  "3215": ["hands reversed clasped circular toe touch (male)", "upper legs"],
  "3302": ["handstand", "upper arms"],
  "0471": ["handstand push-up", "upper arms"],
  "1764": ["hanging leg hip raise", "waist"],
  "0472": ["hanging leg raise", "waist"],
  "1761": ["hanging oblique knee raise", "waist"],
  "0473": ["hanging pike", "waist"],
  "0474": ["hanging straight leg hip raise", "waist"],
  "0475": ["hanging straight leg raise", "waist"],
  "0476": ["hanging straight twisting leg hip raise", "waist"],
  "3636": ["high knee against wall", "cardio"],
  "0484": ["hip raise (bent knee)", "waist"],
  "1418": ["hug keens to chest", "upper legs"],
  "3234": ["hyght dumbbell fly", "chest"],
  "0489": ["hyperextension", "back"],
  "0488": ["hyperextension (on bench)", "back"],
  "3289": ["impossible dips", "upper arms"],
  "1471": ["inchworm", "waist"],
  "3698": ["inchworm v. 2", "waist"],
  "0490": ["incline close-grip push-up", "upper arms"],
  "0491": ["incline leg hip raise (leg straight)", "waist"],
  "0492": ["incline push up depth jump", "chest"],
  "0493": ["incline push-up", "chest"],
  "3785": ["incline push-up (on box)", "chest"],
  "0494": ["incline reverse grip push-up", "chest"],
  "3011": ["incline scapula push up", "chest"],
  "0495": ["incline twisting sit-up", "waist"],
  "1564": ["intermediate hip flexor and quad stretch", "upper legs"],
  "0496": ["inverse leg curl (bench support)", "upper legs"],
  "2400": ["inverse leg curl (on pull-up cable machine)", "upper legs"],
  "0499": ["inverted row", "back"],
  "2300": ["inverted row bent knees", "back"],
  "2298": ["inverted row on bench", "back"],
  "0497": ["inverted row v. 2", "back"],
  "0498": ["inverted row with straps", "back"],
  "1419": ["iron cross stretch", "upper legs"],
  "1297": ["isometric chest squeeze", "chest"],
  "0500": ["isometric wipers", "chest"],
  "0501": ["jack burpee", "cardio"],
  "3224": ["jack jump (male)", "cardio"],
  "0507": ["jackknife sit-up", "waist"],
  "0508": ["janda sit-up", "waist"],
  "2612": ["jump rope", "cardio"],
  "0514": ["jump squat", "upper legs"],
  "0513": ["jump squat v. 2", "upper legs"],
  "0517": ["kettlebell advanced windmill", "waist"],
  "0518": ["kettlebell alternating hang clean", "lower arms"],
  "0520": ["kettlebell alternating press", "shoulders"],
  "0519": ["kettlebell alternating press on floor", "chest"],
  "0521": ["kettlebell alternating renegade row", "back"],
  "0522": ["kettlebell alternating row", "back"],
  "0523": ["kettlebell arnold press", "shoulders"],
  "0524": ["kettlebell bent press", "waist"],
  "0525": ["kettlebell bottoms up clean from the hang position", "upper arms"],
  "0526": ["kettlebell double alternating hang clean", "upper arms"],
  "0527": ["kettlebell double jerk", "shoulders"],
  "0528": ["kettlebell double push press", "shoulders"],
  "0529": ["kettlebell double snatch", "shoulders"],
  "0530": ["kettlebell double windmill", "waist"],
  "0531": ["kettlebell extended range one arm press on floor", "chest"],
  "0532": ["kettlebell figure 8", "waist"],
  "0533": ["kettlebell front squat", "upper legs"],
  "0534": ["kettlebell goblet squat", "upper legs"],
  "0535": ["kettlebell hang clean", "upper legs"],
  "0536": ["kettlebell lunge pass through", "upper legs"],
  "0537": ["kettlebell one arm clean and jerk", "shoulders"],
  "1298": ["kettlebell one arm floor press", "chest"],
  "0538": ["kettlebell one arm jerk", "shoulders"],
  "0539": ["kettlebell one arm military press to the side", "shoulders"],
  "0540": ["kettlebell one arm push press", "shoulders"],
  "0541": ["kettlebell one arm row", "back"],
  "0542": ["kettlebell one arm snatch", "shoulders"],
  "0543": ["kettlebell pirate supper legs", "shoulders"],
  "0544": ["kettlebell pistol squat", "upper legs"],
  "0545": ["kettlebell plyo push-up", "chest"],
  "0546": ["kettlebell seated press", "shoulders"],
  "1438": ["kettlebell seated two arm military press", "shoulders"],
  "0547": ["kettlebell seesaw press", "shoulders"],
  "0548": ["kettlebell sumo high pull", "back"],
  "0549": ["kettlebell swing", "upper legs"],
  "0550": ["kettlebell thruster", "shoulders"],
  "0551": ["kettlebell turkish get up (squat style)", "upper legs"],
  "0552": ["kettlebell two arm clean", "shoulders"],
  "0553": ["kettlebell two arm military press", "shoulders"],
  "1345": ["kettlebell two arm row", "back"],
  "0554": ["kettlebell windmill", "waist"],
  "0555": ["kick out sit", "upper legs"],
  "0558": ["kipping muscle up", "back"],
  "3640": ["knee touch crunch", "waist"],
  "1420": ["kneeling jump squat", "upper legs"],
  "1346": ["kneeling lat stretch", "back"],
  "3239": ["kneeling plank tap shoulder (male)", "waist"],
  "3211": ["kneeling push-up (male)", "chest"],
  "3288": ["korean dips", "chest"],
  "3418": ["l-pull-up", "back"],
  "3419": ["l-sit on floor", "waist"],
  "0562": ["landmine 180", "waist"],
  "3237": ["landmine lateral raise", "shoulders"],
  "3300": ["lean planche", "waist"],
  "2271": ["left hook. boxing", "shoulders"],
  "0570": ["leg pull in flat bench", "waist"],
  "1576": ["leg up hamstring stretch", "upper legs"],
  "2287": ["lever alternate leg press", "upper legs"],
  "0571": ["lever alternating narrow grip seated row", "back"],
  "0572": ["lever assisted chin-up", "back"],
  "0573": ["lever back extension", "back"],
  "0574": ["lever bent over row", "back"],
  "3200": ["lever bent-over row with v-bar", "back"],
  "0575": ["lever bicep curl", "upper arms"],
  "2289": ["lever calf press", "lower legs"],
  "0577": ["lever chest press", "chest"],
  "0576": ["lever chest press", "chest"],
  "0578": ["lever deadlift", "upper legs"],
  "1300": ["lever decline chest press", "chest"],
  "1253": ["lever donkey calf raise", "lower legs"],
  "0579": ["lever front pulldown", "back"],
  "0580": ["lever gripless shrug", "back"],
  "1439": ["lever gripless shrug v. 2", "back"],
  "2288": ["lever gripper hands", "lower arms"],
  "1615": ["lever hammer grip preacher curl", "upper arms"],
  "0581": ["lever high row", "back"],
  "2286": ["lever hip extension v. 2", "upper legs"],
  "2611": ["lever horizontal one leg press", "upper legs"],
  "1299": ["lever incline chest press", "chest"],
  "1479": ["lever incline chest press v. 2", "chest"],
  "0582": ["lever kneeling leg curl", "upper legs"],
  "0583": ["lever kneeling twist", "waist"],
  "0584": ["lever lateral raise", "shoulders"],
  "0585": ["lever leg extension", "upper legs"],
  "0586": ["lever lying leg curl", "upper legs"],
  "3195": ["lever lying two-one leg curl", "upper legs"],
  "0587": ["lever military press", "shoulders"],
  "0588": ["lever narrow grip seated row", "back"],
  "0589": ["lever one arm bent over row", "back"],
  "1356": ["lever one arm lateral high row", "back"],
  "1347": ["lever one arm lateral wide pulldown", "back"],
  "0590": ["lever one arm shoulder press", "shoulders"],
  "0591": ["lever overhand triceps dip", "upper arms"],
  "0592": ["lever preacher curl", "upper arms"],
  "1614": ["lever preacher curl v. 2", "upper arms"],
  "2285": ["lever pullover", "back"],
  "2736": ["lever reverse grip lateral pulldown", "back"],
  "1616": ["lever reverse grip preacher curl", "upper arms"],
  "1348": ["lever reverse grip vertical row", "back"],
  "0593": ["lever reverse hyperextension", "upper legs"],
  "1349": ["lever reverse t-bar row", "back"],
  "2315": ["lever rotary calf", "lower legs"],
  "2335": ["lever seated calf press", "lower legs"],
  "0594": ["lever seated calf raise", "lower legs"],
  "1452": ["lever seated crunch", "waist"],
  "0595": ["lever seated crunch (chest pad)", "waist"],
  "3760": ["lever seated crunch v. 2", "waist"],
  "1451": ["lever seated dip", "upper arms"],
  "0596": ["lever seated fly", "chest"],
  "3759": ["lever seated good morning", "upper legs"],
  "0597": ["lever seated hip abduction", "upper legs"],
  "0598": ["lever seated hip adduction", "upper legs"],
  "0599": ["lever seated leg curl", "upper legs"],
  "0600": ["lever seated leg raise crunch", "waist"],
  "0602": ["lever seated reverse fly", "shoulders"],
  "0601": ["lever seated reverse fly (parallel grip)", "shoulders"],
  "1350": ["lever seated row", "back"],
  "1385": ["lever seated squat calf raise on leg press machine", "lower legs"],
  "0603": ["lever shoulder press", "shoulders"],
  "0869": ["lever shoulder press v. 2", "shoulders"],
  "2318": ["lever shoulder press v. 3", "shoulders"],
  "0604": ["lever shrug", "back"],
  "0605": ["lever standing calf raise", "lower legs"],
  "3758": ["lever standing chest press", "chest"],
  "0606": ["lever t bar row", "back"],
  "1351": ["lever t-bar reverse grip row", "back"],
  "0607": ["lever triceps extension", "upper arms"],
  "1313": ["lever unilateral row", "back"],
  "0609": ["london bridge", "back"],
  "3013": ["low glute bridge on floor", "upper legs"],
  "1352": ["lower back curl", "back"],
  "3582": ["lunge with jump", "upper legs"],
  "1688": ["lunge with twist", "waist"],
  "0613": ["lying (side) quads stretch", "upper legs"],
  "2312": ["lying elbow to knee", "waist"],
  "0620": ["lying leg raise flat bench", "waist"],
  "0865": ["lying leg-hip raise", "waist"],
  "1301": ["machine inner chest press", "chest"],
  "0624": ["march sit (wall)", "upper legs"],
  "1353": ["medicine ball catch and overhead throw", "back"],
  "1302": ["medicine ball chest pass", "chest"],
  "1303": ["medicine ball chest push from 3 point stance", "chest"],
  "1304": ["medicine ball chest push multiple response", "chest"],
  "1305": ["medicine ball chest push single response", "chest"],
  "1312": ["medicine ball chest push with run release", "chest"],
  "1701": ["medicine ball close grip push up", "upper arms"],
  "1354": ["medicine ball overhead slam", "back"],
  "1750": ["medicine ball supine chest throw", "upper arms"],
  "0627": ["mixed grip chin-up", "back"],
  "3217": ["modified hindu push-up (male)", "chest"],
  "1421": ["modified push up to lower arms", "lower arms"],
  "0628": ["monster walk", "upper legs"],
  "0630": ["mountain climber", "cardio"],
  "0631": ["muscle up", "back"],
  "1401": ["muscle-up (on vertical bar)", "back"],
  "2328": ["narrow push-up on exercise ball", "upper arms"],
  "1403": ["neck side stretch", "neck"],
  "0634": ["negative crunch", "waist"],
  "1495": ["oblique crunch v. 2", "waist"],
  "0635": ["oblique crunches floor", "waist"],
  "0636": ["olympic barbell hammer curl", "upper arms"],
  "0637": ["olympic barbell triceps extension", "upper arms"],
  "1355": ["one arm against wall", "back"],
  "0638": ["one arm chin-up", "back"],
  "0639": ["one arm dip", "upper arms"],
  "0640": ["one arm slam (with medicine ball)", "waist"],
  "1773": ["one arm towel row", "back"],
  "1386": ["one leg donkey calf raise", "lower legs"],
  "1387": ["one leg floor calf raise", "lower legs"],
  "1476": ["one leg squat", "upper legs"],
  "0641": ["otis up", "waist"],
  "0642": ["outside leg kick push-up", "upper legs"],
  "0643": ["overhead triceps stretch", "upper arms"],
  "3147": ["pelvic tilt", "waist"],
  "1422": ["pelvic tilt into bridge", "upper legs"],
  "1388": ["peroneals stretch", "lower legs"],
  "3662": ["pike-to-cobra push-up", "upper legs"],
  "1306": ["plyo push up", "chest"],
  "1687": ["posterior step to overhead reach", "waist"],
  "1389": ["posterior tibialis stretch", "lower legs"],
  "3119": ["potty squat", "waist"],
  "3132": ["potty squat with support", "upper legs"],
  "0648": ["power clean", "upper legs"],
  "3665": ["power point plank", "waist"],
  "3203": ["prisoner half sit-up (male)", "waist"],
  "1707": ["prone twist on stability ball", "waist"],
  "0651": ["pull up (neutral grip)", "back"],
  "0650": ["pull-in (on stability ball)", "waist"],
  "0652": ["pull-up", "back"],
  "1689": ["push and pull bodyweight", "chest"],
  "3638": ["push to run", "cardio"],
  "1307": ["push up on bosu ball", "chest"],
  "0662": ["push-up", "chest"],
  "0653": ["push-up (bosu ball)", "chest"],
  "0655": ["push-up (on stability ball)", "chest"],
  "0656": ["push-up (on stability ball)", "chest"],
  "0659": ["push-up (wall)", "chest"],
  "0658": ["push-up (wall) v. 2", "chest"],
  "0660": ["push-up close-grip off dumbbell", "upper arms"],
  "0661": ["push-up inside leg kick", "upper legs"],
  "0663": ["push-up medicine ball", "chest"],
  "1467": ["push-up on lower arms", "upper arms"],
  "3145": ["push-up plus", "chest"],
  "0664": ["push-up to side plank", "waist"],
  "3533": ["quads", "upper legs"],
  "3201": ["quarter sit-up", "waist"],
  "3552": ["quick feet v. 2", "upper legs"],
  "0666": ["raise single arm push-up", "chest"],
  "0668": ["rear decline bridge", "upper legs"],
  "0669": ["rear deltoid stretch", "shoulders"],
  "0670": ["rear pull-up", "back"],
  "1582": ["reclining big toe pose with rope", "upper legs"],
  "3236": ["resistance band hip thrusts on knees (female)", "upper legs"],
  "3007": ["resistance band leg extension", "upper legs"],
  "3123": ["resistance band seated biceps curl", "upper arms"],
  "3124": ["resistance band seated chest press", "chest"],
  "3006": ["resistance band seated hip abduction", "upper legs"],
  "3122": ["resistance band seated shoulder press", "shoulders"],
  "3144": ["resistance band seated straight back row", "back"],
  "0872": ["reverse crunch", "waist"],
  "0672": ["reverse dip", "upper arms"],
  "0673": ["reverse grip machine lat pulldown", "back"],
  "0674": ["reverse grip pull-up", "back"],
  "0675": ["reverse hyper extension (on stability ball)", "upper legs"],
  "1423": ["reverse hyper on flat bench", "upper legs"],
  "3663": ["reverse plank with leg lift", "waist"],
  "0677": ["ring dips", "upper arms"],
  "2571": ["rocking frog stretch", "upper legs"],
  "0678": ["rocky pull-up pulldown", "back"],
  "2208": ["roller back stretch", "back"],
  "2204": ["roller body saw", "waist"],
  "2205": ["roller hip lat stretch", "upper legs"],
  "2202": ["roller hip stretch", "upper legs"],
  "2206": ["roller reverse crunch", "waist"],
  "2203": ["roller seated shoulder flexor depresor retractor", "chest"],
  "2209": ["roller seated single leg shoulder flexor depresor retractor", "chest"],
  "2207": ["roller side lat stretch", "back"],
  "0680": ["rope climb", "back"],
  "0685": ["run", "cardio"],
  "0684": ["run (equipment)", "cardio"],
  "1585": ["runners stretch", "upper legs"],
  "0687": ["russian twist", "waist"],
  "3012": ["scapula dips", "back"],
  "3021": ["scapula push-up", "chest"],
  "0688": ["scapular pull-up", "back"],
  "3219": ["scissor jumps (male)", "cardio"],
  "1390": ["seated calf stretch (male)", "lower legs"],
  "1424": ["seated glute stretch", "upper legs"],
  "0689": ["seated leg raise", "waist"],
  "0690": ["seated lower back stretch", "back"],
  "2567": ["seated piriformis stretch", "upper legs"],
  "0691": ["seated side crunch (wall)", "waist"],
  "1587": ["seated wide angle pose sequence", "upper legs"],
  "0697": ["self assisted inverse leg curl", "upper legs"],
  "1766": ["self assisted inverse leg curl", "upper legs"],
  "0696": ["self assisted inverse leg curl (on floor)", "upper legs"],
  "3222": ["semi squat jump (male)", "cardio"],
  "3656": ["short stride run", "cardio"],
  "1763": ["shoulder grip pull-up", "back"],
  "3699": ["shoulder tap", "waist"],
  "0699": ["shoulder tap push-up", "chest"],
  "1774": ["side bridge hip abduction", "upper legs"],
  "0705": ["side bridge v. 2", "waist"],
  "0709": ["side hip (on parallel bars)", "waist"],
  "0710": ["side hip abduction", "upper legs"],
  "1358": ["side lying floor stretch", "back"],
  "3667": ["side lying hip adduction (male)", "upper legs"],
  "1775": ["side plank hip adduction", "upper legs"],
  "0716": ["side push neck stretch", "neck"],
  "0717": ["side push-up", "upper arms"],
  "0721": ["side wrist pull stretch", "lower arms"],
  "0720": ["side-to-side chin", "back"],
  "3213": ["side-to-side toe touch (male)", "waist"],
  "0725": ["single arm push-up", "chest"],
  "3645": ["single leg bridge with outstretched leg", "upper legs"],
  "0727": ["single leg calf raise (on a dumbbell)", "lower legs"],
  "0730": ["single leg platform slide", "upper legs"],
  "1759": ["single leg squat (pistol) male", "upper legs"],
  "1489": ["sissy squat", "upper legs"],
  "0735": ["sit-up v. 2", "waist"],
  "3679": ["sit-up with arms on chest", "waist"],
  "3361": ["skater hops", "cardio"],
  "2142": ["ski ergometer", "upper arms"],
  "3671": ["ski step", "cardio"],
  "3304": ["skin the cat", "back"],
  "1425": ["sled 45 degrees one leg press", "upper legs"],
  "0738": ["sled 45° calf press", "lower legs"],
  "0739": ["sled 45° leg press", "upper legs"],
  "1464": ["sled 45° leg press (back pov)", "upper legs"],
  "1463": ["sled 45° leg press (side pov)", "upper legs"],
  "0740": ["sled 45° leg wide press", "upper legs"],
  "1391": ["sled calf press on leg press", "lower legs"],
  "0741": ["sled closer hack squat", "upper legs"],
  "0742": ["sled forward angled calf raise", "lower legs"],
  "0743": ["sled hack squat", "upper legs"],
  "2334": ["sled lying calf press", "lower legs"],
  "0744": ["sled lying squat", "upper legs"],
  "1392": ["sled one leg calf press on leg press", "lower legs"],
  "1496": ["sledge hammer", "waist"],
  "0746": ["smith back shrug", "back"],
  "0747": ["smith behind neck press", "shoulders"],
  "0748": ["smith bench press", "chest"],
  "0749": ["smith bent knee good morning", "upper legs"],
  "1359": ["smith bent over row", "back"],
  "0750": ["smith chair squat", "upper legs"],
  "0751": ["smith close-grip bench press", "upper arms"],
  "0752": ["smith deadlift", "upper legs"],
  "0753": ["smith decline bench press", "chest"],
  "0754": ["smith decline reverse-grip press", "chest"],
  "1433": ["smith front squat (clean grip)", "upper legs"],
  "3281": ["smith full squat", "upper legs"],
  "0755": ["smith hack squat", "upper legs"],
  "0756": ["smith hip raise", "waist"],
  "0757": ["smith incline bench press", "chest"],
  "0758": ["smith incline reverse-grip press", "chest"],
  "0759": ["smith incline shoulder raises", "chest"],
  "0760": ["smith leg press", "upper legs"],
  "1434": ["smith low bar squat", "upper legs"],
  "1683": ["smith machine bicep curl", "upper arms"],
  "1625": ["smith machine decline close grip bench press", "upper arms"],
  "1752": ["smith machine incline tricep extension", "upper arms"],
  "1626": ["smith machine reverse decline close grip bench press", "chest"],
  "0761": ["smith narrow row", "back"],
  "1360": ["smith one arm row", "back"],
  "1393": ["smith one leg floor calf raise", "lower legs"],
  "0762": ["smith rear delt row", "shoulders"],
  "0763": ["smith reverse calf raises", "lower legs"],
  "1394": ["smith reverse calf raises", "lower legs"],
  "1361": ["smith reverse grip bent over row", "back"],
  "0764": ["smith reverse-grip press", "chest"],
  "1395": ["smith seated one leg calf raise", "lower legs"],
  "0765": ["smith seated shoulder press", "shoulders"],
  "1426": ["smith seated wrist curl", "lower arms"],
  "0766": ["smith shoulder press", "shoulders"],
  "0767": ["smith shrug", "back"],
  "0768": ["smith single leg split squat", "upper legs"],
  "0769": ["smith sprint lunge", "upper legs"],
  "0770": ["smith squat", "upper legs"],
  "0771": ["smith standing back wrist curl", "lower arms"],
  "0772": ["smith standing behind head military press", "shoulders"],
  "0773": ["smith standing leg calf raise", "lower legs"],
  "0774": ["smith standing military press", "shoulders"],
  "3142": ["smith sumo squat", "upper legs"],
  "1396": ["smith toe raise", "lower legs"],
  "0775": ["smith upright row", "shoulders"],
  "1308": ["smith wide grip bench press", "chest"],
  "1309": ["smith wide grip decline bench press", "chest"],
  "0776": ["snatch pull", "upper legs"],
  "0777": ["spell caster", "waist"],
  "1362": ["sphinx", "back"],
  "0778": ["spider crawl push up", "upper legs"],
  "1363": ["spine stretch", "back"],
  "2329": ["spine twist", "waist"],
  "2368": ["split squats", "upper legs"],
  "0786": ["squat jerk", "upper legs"],
  "1705": ["squat on bosu ball", "upper legs"],
  "1685": ["squat to overhead reach", "upper legs"],
  "1686": ["squat to overhead reach with twist", "upper legs"],
  "2297": ["stability ball crunch (full range hands behind head)", "waist"],
  "3291": ["stalder press", "upper arms"],
  "3669": ["standing archer", "back"],
  "0788": ["standing behind neck press", "shoulders"],
  "1490": ["standing calf raise (on a staircase)", "lower legs"],
  "1397": ["standing calves", "lower legs"],
  "1398": ["standing calves calf stretch", "lower legs"],
  "1599": ["standing hamstring and calf stretch with strap", "upper legs"],
  "0794": ["standing lateral stretch", "back"],
  "1364": ["standing pelvic tilt", "back"],
  "0795": ["standing single leg curl", "upper legs"],
  "0796": ["standing wheel rollerout", "waist"],
  "3223": ["star jump (male)", "cardio"],
  "2138": ["stationary bike run v. 3", "cardio"],
  "0798": ["stationary bike walk", "cardio"],
  "3314": ["straddle maltese", "waist"],
  "3298": ["straddle planche", "waist"],
  "1427": ["straight leg outer hip abductor", "upper legs"],
  "0803": ["superman push-up", "chest"],
  "0805": ["suspended abdominal fallout", "waist"],
  "0806": ["suspended push-up", "chest"],
  "0807": ["suspended reverse crunch", "waist"],
  "0808": ["suspended row", "back"],
  "0809": ["suspended split squat", "upper legs"],
  "3433": ["swimmer kicks v. 2 (male)", "upper legs"],
  "3318": ["swing 360", "cardio"],
  "1753": ["three bench dip", "upper arms"],
  "2459": ["tire flip", "upper legs"],
  "0811": ["trap bar deadlift", "upper legs"],
  "0814": ["triceps dip", "upper arms"],
  "0812": ["triceps dip (bench leg)", "upper arms"],
  "0813": ["triceps dip (between benches)", "upper arms"],
  "0815": ["triceps dips floor", "upper arms"],
  "0816": ["triceps press", "upper arms"],
  "0817": ["triceps stretch", "upper arms"],
  "0871": ["tuck crunch", "waist"],
  "0818": ["twin handle parallel grip lat pulldown", "back"],
  "1466": ["twist hip lift", "upper legs"],
  "2802": ["twisted leg raise", "waist"],
  "2801": ["twisted leg raise (female)", "waist"],
  "3231": ["two toe touch (male)", "back"],
  "1365": ["upper back stretch", "back"],
  "1366": ["upward facing dog", "back"],
  "3420": ["v-sit on floor", "waist"],
  "0826": ["vertical leg raise (on parallel bars)", "waist"],
  "2141": ["walk elliptical cross trainer", "cardio"],
  "3655": ["walking high knees lunge", "cardio"],
  "1460": ["walking lunge", "upper legs"],
  "3666": ["walking on incline treadmill", "cardio"],
  "2311": ["walking on stepmill", "cardio"],
  "0830": ["weighted bench dip", "upper arms"],
  "2987": ["weighted close grip chin-up on dip cage", "back"],
  "3643": ["weighted cossack squats (male)", "upper legs"],
  "0832": ["weighted crunch", "waist"],
  "3670": ["weighted decline sit-up", "waist"],
  "0833": ["weighted donkey calf raise", "lower legs"],
  "1310": ["weighted drop push up", "chest"],
  "2135": ["weighted front plank", "waist"],
  "0834": ["weighted front raise", "shoulders"],
  "0866": ["weighted hanging leg-hip raise", "waist"],
  "0835": ["weighted hyperextension (on stability ball)", "back"],
  "3641": ["weighted kneeling step with swing", "shoulders"],
  "3644": ["weighted lunge with swing", "upper legs"],
  "3286": ["weighted muscle up", "back"],
  "3312": ["weighted muscle up (on bar)", "back"],
  "3290": ["weighted one hand pull up", "back"],
  "0840": ["weighted overhead crunch (on stability ball)", "waist"],
  "0841": ["weighted pull-up", "back"],
  "0844": ["weighted round arm", "shoulders"],
  "0846": ["weighted russian twist", "waist"],
  "0845": ["weighted russian twist (legs up)", "waist"],
  "2371": ["weighted russian twist v. 2", "waist"],
  "0847": ["weighted seated bicep curl (on stability ball)", "upper arms"],
  "0849": ["weighted seated twist (on stability ball)", "waist"],
  "0850": ["weighted side bend (on stability ball)", "waist"],
  "0851": ["weighted sissy squat", "upper legs"],
  "0852": ["weighted squat", "upper legs"],
  "0853": ["weighted standing curl", "upper arms"],
  "0854": ["weighted standing hand squeeze", "lower arms"],
  "3313": ["weighted straight bar dip", "chest"],
  "3642": ["weighted stretch lunge", "upper legs"],
  "0856": ["weighted svend press", "chest"],
  "1754": ["weighted three bench dips", "upper arms"],
  "1755": ["weighted tricep dips", "upper arms"],
  "1767": ["weighted triceps dip on high parallel bars", "upper arms"],
  "0857": ["wheel rollerout", "waist"],
  "3637": ["wheel run", "cardio"],
  "1429": ["wide grip pull-up", "back"],
  "1367": ["wide grip rear pull-up", "back"],
  "1311": ["wide hand push up", "chest"],
  "2363": ["wide-grip chest dip on high parallel bars", "chest"],
  "0858": ["wind sprints", "waist"],
  "1604": ["world greatest stretch", "upper legs"],
  "1428": ["wrist circles", "lower arms"],
  "0859": ["wrist rollerer", "lower arms"],
};
