#!/usr/bin/env node
/**
 * sync-mods — scans mods/<id>/agent-guild.mod.json, validates each manifest, and
 * generates the static registries core imports (src/lib/mods/generated/*).
 *
 * Next.js bundles code at build time, so "installing" a mod = drop a folder
 * into mods/ and run `npm run dev` / `npm run build` (both call this first).
 *
 *   node scripts/sync-mods.mjs            invalid mods are skipped with a warning
 *   node scripts/sync-mods.mjs --strict   any invalid mod fails the run (used by build)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const APP_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MODS_DIR = path.join(APP_ROOT, "mods");
const OUT_DIR = path.join(APP_ROOT, "src/lib/mods/generated");
const AGENT_GUILD_API_VERSION = 1;
const PERMISSIONS = Object.keys(
  JSON.parse(fs.readFileSync(path.join(APP_ROOT, "src/lib/mods/permissions.json"), "utf8")),
);
const ID_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const SEMVER_RE = /^\d+\.\d+\.\d+(-[\w.]+)?$/;
const EXTS = [".tsx", ".ts", ".jsx", ".js"];

/** Returns a list of problems (empty = valid). `modDir` is used to check entry files exist. */
export function validateManifest(m, folderName, modDir) {
  const errors = [];
  if (!m || typeof m !== "object") return ["manifest must be a JSON object"];
  if (typeof m.id !== "string" || !ID_RE.test(m.id)) errors.push("id must be kebab-case");
  else if (m.id !== folderName) errors.push(`id "${m.id}" must equal folder name "${folderName}"`);
  if (typeof m.name !== "string" || !m.name.trim()) errors.push("name is required");
  if (typeof m.version !== "string" || !SEMVER_RE.test(m.version)) errors.push("version must be semver (1.0.0)");
  if (m.agentGuildApi !== AGENT_GUILD_API_VERSION) errors.push(`agentGuildApi must be ${AGENT_GUILD_API_VERSION} (got ${JSON.stringify(m.agentGuildApi)})`);
  if (!Array.isArray(m.permissions)) errors.push("permissions must be an array (use [] for none)");
  else for (const p of m.permissions) if (!PERMISSIONS.includes(p)) errors.push(`unknown permission "${p}" (known: ${PERMISSIONS.join(", ")})`);

  const entry = m.entry;
  if (!entry || typeof entry !== "object" || (!entry.client && !entry.server)) {
    errors.push("entry must define at least one of client/server");
  } else if (modDir) {
    for (const side of ["client", "server"]) {
      if (entry[side] && !resolveEntry(modDir, entry[side])) errors.push(`entry.${side} "${entry[side]}" not found`);
    }
  }

  if (m.panels !== undefined) {
    if (!Array.isArray(m.panels)) errors.push("panels must be an array");
    else {
      if (m.panels.length && !entry?.client) errors.push("panels require entry.client");
      const seen = new Set();
      for (const p of m.panels) {
        if (typeof p?.id !== "string" || !ID_RE.test(p.id)) errors.push(`panel id "${p?.id}" must be kebab-case`);
        else if (seen.has(p.id)) errors.push(`duplicate panel id "${p.id}"`);
        else seen.add(p.id);
        if (typeof p?.title !== "string" || !p.title.trim()) errors.push(`panel "${p?.id}" needs a title`);
      }
    }
  }
  return errors;
}

/** Find entry file (extension optional) → path relative to modDir without extension, or null. */
function resolveEntry(modDir, rel) {
  const base = path.join(modDir, rel);
  if (fs.existsSync(base) && fs.statSync(base).isFile()) return rel.replace(/\.[jt]sx?$/, "");
  for (const ext of EXTS) if (fs.existsSync(base + ext)) return rel;
  return null;
}

function scan() {
  const mods = [];
  const problems = [];
  if (!fs.existsSync(MODS_DIR)) return { mods, problems };
  for (const dirent of fs.readdirSync(MODS_DIR, { withFileTypes: true })) {
    if (!dirent.isDirectory() || dirent.name.startsWith(".") || dirent.name.startsWith("_")) continue;
    const modDir = path.join(MODS_DIR, dirent.name);
    const manifestPath = path.join(modDir, "agent-guild.mod.json");
    if (!fs.existsSync(manifestPath)) {
      problems.push(`${dirent.name}: no agent-guild.mod.json`);
      continue;
    }
    let manifest;
    try {
      manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    } catch (e) {
      problems.push(`${dirent.name}: agent-guild.mod.json is not valid JSON (${e.message})`);
      continue;
    }
    const errors = validateManifest(manifest, dirent.name, modDir);
    if (errors.length) errors.forEach((e) => problems.push(`${dirent.name}: ${e}`));
    else mods.push({ manifest, dir: dirent.name, modDir });
  }
  mods.sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));
  return { mods, problems };
}

function generate(mods) {
  const header = "// AUTO-GENERATED by scripts/sync-mods.mjs — do not edit. Run `npm run mods:sync`.\n";
  const loaders = (side) =>
    mods
      .filter((m) => m.manifest.entry[side])
      .map((m) => {
        const rel = resolveEntry(m.modDir, m.manifest.entry[side]).replace(/^\.\//, "");
        return `  ${JSON.stringify(m.manifest.id)}: () => import(${JSON.stringify(`../../../../mods/${m.dir}/${rel}`)}),`;
      })
      .join("\n");

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(OUT_DIR, "manifests.ts"),
    `${header}import type { ModManifest } from "@agent-guild/sdk";\n\nexport const MOD_MANIFESTS: ModManifest[] = ${JSON.stringify(mods.map((m) => m.manifest), null, 2)};\n`,
  );
  fs.writeFileSync(
    path.join(OUT_DIR, "server.ts"),
    `${header}import type { ServerMod } from "@agent-guild/sdk";\n\nexport const serverMods: Record<string, () => Promise<{ default: ServerMod }>> = {\n${loaders("server")}\n};\n`,
  );
  fs.writeFileSync(
    path.join(OUT_DIR, "client.ts"),
    `${header}import type { ClientMod } from "@agent-guild/sdk";\n\nexport const clientMods: Record<string, () => Promise<{ default: ClientMod }>> = {\n${loaders("client")}\n};\n`,
  );
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const strict = process.argv.includes("--strict");
  const { mods, problems } = scan();
  generate(mods);
  console.log(`[mods] ${mods.length} mod(s): ${mods.map((m) => m.manifest.id).join(", ") || "none"}`);
  for (const p of problems) console.warn(`[mods] ⚠ ${p}`);
  if (strict && problems.length) {
    console.error("[mods] Refusing to continue: fix the mods above or remove them.");
    process.exit(1);
  }
}
