import { describe, it, expect } from "vitest";
import { recoverTypedDataAddress, type Hex } from "viem";
import {
  actionHash,
  floatToWire,
  nextNonce,
  orderAction,
  orderWire,
  signL1Action,
  type L1Action,
} from "../../../../mods/hyperliquid-trading/signing";
import vectors from "./fixtures/hyperliquid-signing-vectors.json";

// Fixture generated by the official hyperliquid-python-sdk (sign_l1_action,
// action_hash, float_to_wire) with a throwaway key — a TS signature that
// matches it is one Hyperliquid will accept.

describe("hyperliquid signing parity with the Python SDK", () => {
  it.each(vectors.floats)("floatToWire(%s) = %s", (x, wire) => {
    expect(floatToWire(x as number)).toBe(wire);
  });

  it("refuses to round silently", () => {
    expect(() => floatToWire(0.123456789)).toThrow();
  });

  for (const c of vectors.cases) {
    it(`hashes and signs ${c.name} identically`, async () => {
      const action = c.action as L1Action;
      expect(actionHash(action, c.nonce)).toBe(c.hash);
      const sig = await signL1Action(vectors.key, action, c.nonce, c.mainnet);
      // Python's to_hex drops leading zeros; compare the numbers.
      expect(BigInt(sig.r)).toBe(BigInt(c.signature.r));
      expect(BigInt(sig.s)).toBe(BigInt(c.signature.s));
      expect(sig.v).toBe(c.signature.v);
    });
  }

  it("builds order wires in the SDK's exact key order", () => {
    const sl = orderWire({
      asset: 5, isBuy: false, sz: 2.5, limitPx: 95.5, reduceOnly: true,
      orderType: { trigger: { triggerPx: 95.5, isMarket: true, tpsl: "sl" } },
    });
    const tp = orderWire({
      asset: 70000, isBuy: false, sz: 2.5, limitPx: 110.25, reduceOnly: true,
      orderType: { trigger: { triggerPx: 110.25, isMarket: true, tpsl: "tp" } },
    });
    const fixture = vectors.cases.find((c) => c.name === "sl-tp-pair")!;
    const built = orderAction([sl, tp]);
    expect(JSON.stringify(built)).toBe(JSON.stringify(fixture.action));
    expect(actionHash(built, fixture.nonce)).toBe(fixture.hash);
  });

  it("signature recovers to the signing address", async () => {
    const c = vectors.cases[0];
    const sig = await signL1Action(vectors.key, c.action as L1Action, c.nonce, c.mainnet);
    const address = await recoverTypedDataAddress({
      domain: { chainId: 1337, name: "Exchange", verifyingContract: "0x0000000000000000000000000000000000000000", version: "1" },
      types: { Agent: [{ name: "source", type: "string" }, { name: "connectionId", type: "bytes32" }] },
      primaryType: "Agent",
      message: { source: c.mainnet ? "a" : "b", connectionId: c.hash as Hex },
      signature: { r: sig.r, s: sig.s, v: BigInt(sig.v) },
    });
    expect(address).toBe(vectors.address);
  });

  it("never repeats a nonce", () => {
    const a = nextNonce();
    const b = nextNonce();
    const c = nextNonce();
    expect(b).toBeGreaterThan(a);
    expect(c).toBeGreaterThan(b);
  });
});
